name: Merge Script
###
on:
  push:
    branches:
      - main  # 替换为你的默认分支
  schedule:
    - cron:  '0 0 * * 0'  # 每周日午夜触发

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # 替换为你的 Python 版本

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run merge script
        run: python meta_merge.py  # 替换为你的 merge.py 脚本名称
      - name: Run shadowrocket merge script
        run: python shadowrocket_merge.py  # 替换为你的 merge.py 脚本名称
      - name: Commit Changes
        run: |
          git config core.ignorecase false
          git config --local user.email "vveg26@gmail.com"
          git config --local user.name "vveg26"
          git add .
          git commit -m "Updated at $(date '+%Y-%m-%d %H:%M:%S')"
          git push
